plugins:
  - rubocop-rails

Style/Documentation:
  Enabled: false
Rails:
  Enabled: true
AllCops:
  NewCops: disable
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
