services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle:/bundle
    environment:
      BUNDLE_PATH: /bundle
      RAILS_ENV: development
    ports:
      - "3000:3000"
    command: bash -lc "bundle exec rails dartsass:build && bundle exec rails server -b 0.0.0.0"

volumes:
  bundle:
